### ISSUE TITLE
Error while parsing psscripts.ini file

### ISSUE THREAD

**Issue by RemiEscourrou** [Group3r/Group3r#2]
The psscripts.ini file can have a specific section ScriptsConfig before the classic Logon / Logoff:

```
[ScriptsConfig]
StartExecutePSFirst=true
EndExecutePSFirst=true
[Logon]
0CmdLine=toto.ps1
0Parameters=
[Logoff]
0CmdLine=toto.ps1
0Parameters=
```

Source : https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gpscr/1e1641a3-a376-4aaa-96b9-4873a3052fd6
>The StartExecutePSFirst key indicates whether the computer startup and user logon scripts listed in psscripts.ini are to be executed before or after the scripts listed in scripts.ini. If unspecified, the order is implementation-dependent.
>The EndExecutePSFirst key indicates whether the computer shutdown and user logoff scripts listed in psscripts.ini are to be executed before or after the scripts listed in scripts.ini. If unspecified, the order is implementation-dependent.

In a security point of view, I'm not sure that is interesting but it actually crashes the IniGpoFile function:

> 2021-09-28 19:31:13 +02:00 [Trace] Looking inside file \\\\XXX\User\Scripts\psscripts.ini for settings.
> 2021-09-28 18:31:13 +02:00 [Error] Something went wrong with the scripts.ini parsing and the int casting and the GLAYVIN!

Indeed, the parsing function is looking for an int and gets an "E" or "S":

>2021-09-28 20:05:04 +02:00 [Trace] Looking inside file \\\\XXX\User\Scripts\psscripts.ini for settings.
>2021-09-28 20:05:04 +02:00 [Trace] Debug lineIndexString S
>2021-09-28 20:05:04 +02:00 [Trace] Debug lineIndexString E
>2021-09-28 20:05:04 +02:00 [Trace] Debug lineIndexString 0
>2021-09-28 20:05:04 +02:00 [Trace] Debug lineIndexString 0
>2021-09-28 20:05:04 +02:00 [Trace] Debug lineIndexString 0
>2021-09-28 20:05:04 +02:00 [Trace] Debug lineIndexString 0

A quick and simple solution could be to ignore this case and allow the parsing of the rest of the ini file:

https://github.com/Group3r/Group3r/blob/6e23e845b233343281a35034c6e27a006911e48c/LibSnaffle/ActiveDirectory/Sysvol/GpoFiles/IniGpoFile.cs#L98

``` C#
if (int.TryParse(lineIndexString, out lineIndex))
{
    if (linesDict.Keys.Contains(lineIndex))
    {
        linesDict[lineIndex].Add(line.Substring(1));
    }
    else
    {
        linesDict.Add(lineIndex, new List<string>() { line.Substring(1) });
    }
}
else if (lineIndexString == "E" | lineIndexString == "S")
{
    Logger.Trace("Ignore StartExecutePSFirst or EndExecutePSFirst configuration");
}
else
{
    if (Logger != null)
    {
        Logger.Error("Something went wrong with the scripts.ini parsing and the int casting and the GLAYVIN!");
    }
}
```

ps: great work for this new version !!!

**Comment by l0ss** [comment]
fixed by #4
