### ISSUE TITLE
Something went real squirrelly in the command line args:  -u, --testuser 

### ISSUE THREAD

**Issue by presianbg** [Group3r/Group3r#7]
Hi,

Using the `-u` switch results in:

```
Unhandled exception in Group3rRunner. Please report the following error directly to l0ss or file an issue in GitHub:
CommandLineParser.Exceptions.CommandLineArgumentException: Something went real squirrelly in the command line args.
   at Group3r.Options.OptionsParser.Parse(String[] args, GrouperMq mq)
   at Group3r.Group3rRunner.Run(String[] args)
2022-04-02 04:01:38 -07:00 [Trace] Requested verbosity level: trace
```

Did I messed up the build process or it's a bug ?

Cheers,
PY

**Comment by l0ss** [comment]
What was the full set of args you were using?

**Comment by presianbg** [comment]
`.\Group3r.exe -c 192.168.1.1 -d test.local -u TEST\user`

I'm running the tool in context of `nt authority\system`

**Comment by l0ss** [comment]
ok yeah good bug, turns out i forgot to actually implement the arg parser for that argument 💀 

I'll fix it up and let you know.

**Comment by l0ss** [comment]
On a domain joined computer?
