### ISSUE TITLE
Targeting a different domain than your user is in does not work

### ISSUE THREAD

**Issue by dirkjanm** [Group3r/Group3r#9]
I tried targeting a different domain than my current user is in, but somehow that doesn't seem to work. 
I've managed to trace the bug down to probably here: https://github.com/Group3r/Group3r/blob/main/LibSnaffle/ActiveDirectory/LDAP/DirectorySearch.cs#L34
There isn't really a reference anywhere in that function to the `domainName` parameter, so it will always default back to the domain of your user rather than the one you specify.

I've worked around this by changing the code to first set the domain name to the parameter value, but not sure if that would break things in different scenarios or code paths:

```diff
--- a/LibSnaffle/ActiveDirectory/LDAP/DirectorySearch.cs
+++ b/LibSnaffle/ActiveDirectory/LDAP/DirectorySearch.cs
@@ -31,8 +31,8 @@ namespace LibSnaffle.ActiveDirectory.LDAP

         public DirectorySearch(string domainName, string domainController, string ldapUserName = null, string ldapPassword = null, int ldapPort = 0, bool secureLdap = false)
         {
+            _domainName = domainName;
             _domain = GetDomain();
-            _domainName = _domain.Name;
             baseLdapPath = $"DC={_domainName.Replace(".", ",DC=")}";
             _domainController = domainController;
             _domainGuidMap = new Dictionary<string, string>();
```

Thanks for the work on this project! 😊

**Comment by l0ss** [comment]
thanks for picking this up - a lot of that part of the code underwent an enormous amount of shuffling trying to make the thing work through a socks proxy by avoiding any methods that try to do an SRV record lookup and then bring the whole thing down when it fails. pretty sure your proposed fix will be fine under that circumstance but you're right to wonder if there might be weird edge-cases. 

I'm a bit slammed with work stuff atm to won't have much time to test properly for a while but I'll leave the issue open and try to get to it asap.

Cheers!
